* ERP: l'area acquisti
** Obiettivi
Si occupano principalmente di definire le caratteristiche di prodotti, fornitori e servizi.\\
Nei sistemi più evoluti oltre a queste funzioni di base esistono procedure per trattare quanto avviene nel settore vendite (flusso attivo).
** Strutture di base
+ Anagrafiche commerciali dei prodotti e fornitori
+ Le strutture per listini e sconti
+ I documenti che registrano i fenomeni di transazione
*** Anagrafiche commerciali
**** Fornitori
I fornitori si distinguono in tre categorie: di materiali, di lavorazioni e di trasporti.\\
Ad ogni fornitore sono associate le informazioni commerciali oltre a quelle anagrafiche di base.
*** Condizioni commerciali
Sono molto più semplici di quelle nei flussi attivi, devono solo contenere prezzi d'acquisto e sconti associati.
**** Listini d'acquisto
Un obbiettivon è registrare l'evoluzione dei prezzi nel tempo, l'unica complessità è data dai dall'esistenza di prezzi a scaglioni analoghi a quelli del flusso attivo.
**** Sconti
Sono simili a quelli del flusso attivo, sono modelizzabili tramite un albero decisionale.
*** Documenti di processo
**** Struttura dei documenti di processo
Come nel flusso attivo i docuemtni sono formati da una testam delle righe e un piede.
+ *Testa:* i dati comuni all'intero documento
  + Identificazione: protocollo, data inserimento, data conferma.
  + Identificazione fornitore
  + Condizioni commerciali: valuta , modalità di pagamento
  + Spedizione: tipo di trasporto
  + Dati generali: tipo di movimentazione logistica, movimentazione contabile e IVA
+ *Righe:*
  + Identificatori della riga
  + Identificatori prodotto o servizio
  + Spedizione
  + Logistica
  + Amministrazione
+ *Piede:*
  + Condizioni commerciali: i vari sconti
  + Totalizzatori: totale documento, totale IVA e scadenza del pagamento
** Procedure di base
Le procedure di base sono divise in due blocchi principali: quelle di supporto al flusso esecutivo e quelle che forniscono le analisi operative.
*** Procedure di flusso
Sono elencate nell'ordine cronologicon in cui vengono eseguite: richiesta d'acquito, preventivazione, emissione ordini, ricezione materiali e controllo fatture.
*** Procedure di analisi
Le analisi che i sistemi ERP offrono sono analoghe a quelle sui flussi attivi, reporting ordinato per vari campi.\\
Date lòe richieste molto mutevoli, vengono utilizzati dei sistemi informazionali con metodologie di data warehousing.
** Flussi evolutivi
Il flusso acquisti (passivo) ha problematiche simmetriche rispetto al flusso attivo, soprattutto se l'azienda ha attività prettamente commerciali o se opera nella grande distribuzione.
*** Condizioni commerciali
**** Gruppi d'acquisto
Se l'azienda aderisce ad un gruppo d'acquisto parte degli acquisti dovrà seguire le direttive date dal capo gruppo.
**** Accordi quadro
Che siano essi legati ad un gruppo di acquisto o trattati autonomamente.
**** Ordini aperti
In modo simmetrico alle vendite, questi ordini definiscono quello che l'azienda si è impegnata a comprare.
*** Processi
**** Validazione
Legata a due lemenete: la tipologia di acquisti e l'entità di essi.\\
Ci sono gerarchie a buyer autorizzati e firme digitali.
**** Controllo qualità
Dopo aver superato un controllo quantitativo si va in un deposito "accettazione" nel quakle vengono fatti controlli qualitativi approfonditi.\\
Gli ERP spesso estrapolano delle valutazioni sui fornitori, ovvero una stima sulla loro qualità considerando la puntualità e la conformità degli articoli.
** Estensioni dell'ERP
*** SCM
La sincronizzazione tra fabisogno dell'azienda e disponibilità dei fornitoriè un punto delicato.\\
Esistono pertanto le SCM (Supply Chain Management), ovvero una catena di fornitura composta da più aziende coinvolta in un unico processo virtuale.
*** E-procurement
Un esempio è il CONSIP per gli appalti pubblici, solitamente gli ERP si interfacciano ad essi tramite servizi web.\\
Sono simmetrici agli e-commerce, forniscono funzioni per:
+ Analizzare il fabisogno di acquisto
+ Gestire le gare
+ Interagire con i fornitori
Mentre ai fornitori permettono di:
+ Gestire le proprie offerte
+ Aggiornare lo stato dell'ordine
